t

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3792,6 +3792,72 @@ _ACEOF
   fi
 
 
+  echo "$as_me:$LINENO: checking for working lstat in sys/stat.h" >&5
+echo $ECHO_N "checking for working lstat in sys/stat.h... $ECHO_C" >&6
+if test "${ac_cv_pts_lstat_in_sys_stat+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+    if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cross compiling not supported by .._PTS_CHECK_HEADER" >&5
+echo "$as_me: error: cross compiling not supported by .._PTS_CHECK_HEADER" >&2;}
+   { (exit 1); exit 1; }; }
+
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+/* #include "confdefs.h" -- automatic */
+#undef const
+#undef volatile
+#undef inline
+#include <sys/stat.h>
+#include "confdefs.h"
+int main
+#ifdef __STDC__
+(int argc, char **argv)
+#else
+(argc, argv) int argc; char **argv;
+#endif
+{
+  struct stat st; return 0!=lstat("/",&st);
+  return 1;
+}
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_pts_lstat_in_sys_stat=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+( exit $ac_status )
+ac_cv_pts_lstat_in_sys_stat=no
+fi
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
+fi
+echo "$as_me:$LINENO: result: $ac_cv_pts_lstat_in_sys_stat" >&5
+echo "${ECHO_T}$ac_cv_pts_lstat_in_sys_stat" >&6
+  if test x"$ac_cv_pts_lstat_in_sys_stat" = xyes; then
+    cat >>confdefs.h <<_ACEOF
+#define HAVE_lstat_in_sys_stat 1
+_ACEOF
+
+  fi
+
+
 
   echo "$as_me:$LINENO: checking for working strcpy in string.h" >&5
 echo $ECHO_N "checking for working strcpy in string.h... $ECHO_C" >&6
@@ -6828,7 +6894,7 @@ fi
 rm -f Makedep
 ac_n="${ac_n:-$ECHO_N}"
 echo $ac_n "running make Makedep""... $ac_c" 1>&6
-echo "configure:6831: running make Makedep" >&5
+echo "configure:6897: running make Makedep" >&5
 if >&5 2>&5 make Makedep; then :
   echo "$as_me:$LINENO: result: ok" >&5
 echo "${ECHO_T}ok" >&6
@@ -6841,7 +6907,7 @@ echo "$as_me: error: cannot compute depends" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-echo "configure:6844: all OK" >&5
+echo "configure:6910: all OK" >&5
 
 echo "configure done. Now you should run: make; make install"
 
